CC = mpicc
CFLAGS = -O2

mpi_bandwidth : mpi_bandwidth.c

# No need to write out the above rule; use GNU Make's built-in rule
# for compiling C programs:
# https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html
